#! /usr/bin/env bash

set -e -o pipefail

if [ $# -ne 0 ]; then
	s=`basename $0`
	echo "usage: $s"
	exit 1
fi


read -p "Are you sure? " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
	[[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1 # handle exits from shell or function but don't exit interactive shell
fi

git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d

